name: canapafarms
favicon: null
layout_spectrum: 0.50731
typography_spectrum: 0.57187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afafaf'
    - '#7c7c7c'
    - '#316d23'
    - '#232611'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
